-- ============================================================
-- 03_create_file_format.sql
-- Define o formato dos arquivos JSON (bronze) e Parquet (silver)
-- ============================================================

USE DATABASE MOVIES_DATABASE;

CREATE TABLE IF NOT EXISTS MOVIES_DATABASE.BRONZE.MOVIES (
    RAW_DATA VARIANT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_FILE STRING
);

CREATE TABLE IF NOT EXISTS MOVIES_DATABASE.BRONZE.UPDATED_MOVIE_IDS (
    RAW_DATA VARIANT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_FILE STRING
);

CREATE TABLE IF NOT EXISTS MOVIES_DATABASE.BRONZE.MOVIES_UPDATES (
    RAW_DATA VARIANT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_FILE STRING
);